# - name: Check if Kubernetes nodes are ready
#   shell: kubectl get nodes --no-headers | awk '{print $2}' | grep -v "Ready"
#   register: node_check
#   until: node_check.stdout_lines | length == 0
#   retries: 60
#   delay: 10
#   ignore_errors: true

- name: Wait for kubernetes api port
  wait_for:
    timeout: 300 
    port: 6443  
    state: started
    delay: 10

- name: "Copy deployment check script"
  copy:
    src: "check_deployment.sh"
    dest: "/root/check_deployment.sh"
    mode: "0755"

- name: Get deployments in kube-system namespace
  shell: bash /root/check_deployment.sh kube-system 


- name: Add a certmanager helm repository
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io

- name: Install certmanager
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    release_namespace: cert-manager
    create_namespace: true
    update_repo_cache: true
    values:
      installCRDs: true

- name: Get deployments in cert-manager namespace
  shell: bash /root/check_deployment.sh cert-manager

- name: Add a rancher helm repository
  kubernetes.core.helm_repository:
    name: rancher-latest
    repo_url: https://releases.rancher.com/server-charts/latest

- name: Install rancher
  kubernetes.core.helm:
    name: rancher
    chart_ref: rancher-latest/rancher
    release_namespace: cattle-system
    create_namespace: true
    update_repo_cache: true
    values:
      hostname: "{{rancher_hostname}}"
      bootstrapPassword: "{{rancher_admin_password}}"

- name: Get deployments in cattle-system namespace
  shell: bash /root/check_deployment.sh cattle-system 
