- name: "Copy deployment check script"
  copy:
    src: "check_deployment.sh"
    dest: "/root/check_deployment.sh"
    mode: "0755"

- name: Get deployments in kube-system namespace
  shell: bash /root/check_deployment.sh kube-system 


- name: Add a longhorn helm repository
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: https://charts.longhorn.io

- name: Install longhorn
  kubernetes.core.helm:
    name: longhorn
    chart_ref: longhorn/longhorn
    release_namespace: longhorn-system
    create_namespace: true
    update_repo_cache: true
    values:
      persistence: 
        defaultClassReplicaCount: "{{ longhorn_default_replica_count |default('1') }}"

- name: Get deployments in longhorn-system namespace
  shell: bash /root/check_deployment.sh longhorn-system

