- name: Upload ssh key
  copy:
    src: "{{ ansible_ssh_private_key_file }}"
    dest: "/root/.ssh/{{ base_domain }}.key"
    mode: "0600"

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install dependencies
  package:
    name:
      - python3
