- name: "Copy deployment check script"
  copy:
    src: "check_deployment.sh"
    dest: "/root/check_deployment.sh"
    mode: "0755"

- name: Install Pip3
  apt:
    name: python3-pip
    update_cache: yes

- name: Install postgres lib
  package:
    name:
      - libpq-dev
      - postgresql


- name: Install kubernetes pre requisites
  pip:
    name: 
      - kubernetes
      - psycopg2

- name: Install oci sdk
  pip:
    name: 
      - pyOpenSSL
      - oci

- name: Remove OpenSSL python packages
  shell: |
    rm -R /usr/lib/python3/dist-packages/OpenSSL
    pip3 install pyOpenSSL --upgrade

- name: Add a reloader helm repository
  kubernetes.core.helm_repository:
    name: stakater
    repo_url: https://stakater.github.io/stakater-charts

- name: Add a daas helm repository
  kubernetes.core.helm_repository:
    name: daas
    repo_url: https://oci-sunbird.github.io/daas-helm

- name: Add a longhorn helm repository
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: https://charts.longhorn.io

- name: Add a cloud native postgres helm repository
  kubernetes.core.helm_repository:
    name: cnpg
    repo_url: https://cloudnative-pg.github.io/charts

- name: Add hashicorp helm repository
  kubernetes.core.helm_repository:
    name: hashicorp
    repo_url: https://helm.releases.hashicorp.com

- name: Add elasticsearch helm repository
  kubernetes.core.helm_repository:
    name: elastic
    repo_url: https://helm.elastic.co

- name: Add a certmanager helm repository
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io

- name: Add a ACME webhook for Oracle Cloud Infrastructure helm repository
  kubernetes.core.helm_repository:
    name: cert-manager-webhook-oci
    repo_url: https://dn13.gitlab.io/cert-manager-webhook-oci

- name: Create project directories
  file:
    path: "{{item}}"
    state: directory
    mode: '0755'
  with_items:
    - /root/sunbird-rc/customization
    - /root/sunbird-rc/customization/longhorn
    - /root/sunbird-rc/customization/postgres
    - /root/sunbird-rc/customization/vault
    - /root/sunbird-rc/customization/filestorage
    - /root/sunbird-rc/customization/keycloak
    - /root/sunbird-rc/customization/registry
    - /root/sunbird-rc/customization/identity
    - /root/sunbird-rc/customization/cert-manager
    - /root/sunbird-rc/customization/outputs

- name: Create a k8s namespace
  kubernetes.core.k8s:
    name: "{{item}}"
    api_version: v1
    kind: Namespace
    state: present
  with_items:
    - sunbird-rc
    - istio-system
