- name: Create project directories
  file:
    path: "{{item}}"
    state: directory
    mode: '0755'
  with_items:
    - /root/sunbird-rc/customization/monitoring


- name: Add a prometheus-community helm repository
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts

- name: Install kube-prometheus-stack
  kubernetes.core.helm:
    name: kube-prometheus-stack
    chart_ref: prometheus-community/kube-prometheus-stack
    chart_version: 61.1.1
    release_namespace: monitoring
    create_namespace: true
    update_repo_cache: true
    values:
      serviceMonitorNamespaceSelector:
        any: true
      serviceMonitorSelector: {}
      serviceMonitorSelectorNilUsesHelmValues: false
      grafana:
        testFramework:
          enabled: false
        dashboardProviders:
          dashboardproviders.yaml:
            apiVersion: 1
            providers:
              - name: "default"
                orgId: 1
                folder: ""
                type: file
                disableDeletion: false
                editable: true
                options:
                  path: /var/lib/grafana/dashboards/default
        # datasources:
        #   datasources.yaml:
        #     apiVersion: 1
        #     datasources:
        #       - name: TemporalMetrics
        #         type: prometheus
        #         url: http://kube-prometheus-stack-prometheus.monitoring:9090/
        #         access: proxy
        #         isDefault: false
        dashboards:
          default:
            server-general-github:
              url: https://raw.githubusercontent.com/temporalio/dashboards/helm/server/server-general.json
              datasource: Prometheus
            sdk-general-github:
              url: https://raw.githubusercontent.com/temporalio/dashboards/helm/sdk/sdk-general.json
              datasource: Prometheus
            misc-advanced-visibility-specific-github:
              url: https://raw.githubusercontent.com/temporalio/dashboards/helm/misc/advanced-visibility-specific.json
              datasource: Prometheus
            misc-clustermonitoring-kubernetes-github:
              url: https://raw.githubusercontent.com/temporalio/dashboards/helm/misc/clustermonitoring-kubernetes.json
              datasource: Prometheus
            misc-frontend-service-specific-github:
              url: https://raw.githubusercontent.com/temporalio/dashboards/helm/misc/frontend-service-specific.json
              datasource: Prometheus
            misc-history-service-specific-github:
              url: https://raw.githubusercontent.com/temporalio/dashboards/helm/misc/history-service-specific.json
              datasource: Prometheus
            misc-matching-service-specific-github:
              url: https://raw.githubusercontent.com/temporalio/dashboards/helm/misc/matching-service-specific.json
              datasource: Prometheus
            misc-worker-service-specific-github:
              url: https://raw.githubusercontent.com/temporalio/dashboards/helm/misc/worker-service-specific.json
              datasource: Prometheus


- name: Wait for deployments in monitoring namespace
  shell: bash /root/check_deployment.sh monitoring


- name: "Update templates"
  template:
    src: "monitoring/{{item}}.j2"
    dest: "/root/sunbird-rc/customization/monitoring/{{item}}"
    mode: '0755'
  with_items:
    - vs_grafana.yaml


- name: Create k8s objects for monitoring
  kubernetes.core.k8s:
    namespace: monitoring
    state: present
    src: /root/sunbird-rc/customization/monitoring/{{item}}
  with_items:
    - vs_grafana.yaml