- name: Include variables from file
  include_vars:
    file: "{{ inventory_dir }}/vault_secrets.yaml"

- name: "Update identity virtual service config"
  template:
    src: "identity/identity-virtual-service.yaml.j2"
    dest: "/root/sunbird-rc/customization/identity/identity-virtual-service.yaml"

- name: Create identity virtual service
  shell: kubectl -n sunbird-rc apply -f /root/sunbird-rc/customization/identity/identity-virtual-service.yaml

- name: Install identity
  kubernetes.core.helm:
    name: identity
    chart_ref: daas/identity
    release_namespace: sunbird-rc
    create_namespace: true
    update_repo_cache: true
    values:
      global:
        host: "sbrciam.{{domain}}"
        sunbird: 
          enable_auth: false 
          signing_algo: Ed25519Signature2020
          jwks_uri: "https://sbrciam.{{domain}}/auth/realms/sunbird-rc/protocol/openid-connect/certs"
        base_urls:
          identity: https://sbrc.{{domain}}/identity
          web_did: https://sbrc.{{domain}}/identity
          credential_schema: https://sbrc.{{domain}}/schema
          credential_service: https://sbrc.{{domain}}/credential
        secrets:
          VAULT_SECRET_TOKEN: "{{vault_root_token |b64encode }}"
          DB_URL: "{{db_url |b64encode}}"

- name: Wait for deployments in sunbird-rc namespace
  shell: bash /root/check_deployment.sh sunbird-rc
