- name: Create project directories
  file:
    path: "{{item}}"
    state: directory
    mode: '0755'
  with_items:
    - /root/sunbird-rc/customization/strimzi

- name: Install strimzi
  kubernetes.core.helm:
    name: strimzi-cluster-operator
    chart_ref: oci://quay.io/strimzi-helm/strimzi-kafka-operator
    chart_version: 0.41.0
    release_namespace: strimzi
    create_namespace: true
    update_repo_cache: true
    values:
      dashboards:
        enabled: true

# - name: Wait for deployments in strimzi namespace
#   shell: bash /root/check_deployment.sh strimzi

- name: "Update templates"
  template:
    src: "strimzi/{{item}}.j2"
    dest: "/root/sunbird-rc/customization/strimzi/{{item}}"
    mode: '0755'
  with_items:
    - kafka_cluster.yaml


- name: Create k8s objects for strimzi
  kubernetes.core.k8s:
    namespace: strimzi
    state: present
    src: /root/sunbird-rc/customization/strimzi/{{item}}
  with_items:
    - kafka_cluster.yaml

