- name: Add a strimzi helm repository
  kubernetes.core.helm_repository:
    name: strimzi
    repo_url: https://strimzi.io/charts

- name: Install strimzi
  kubernetes.core.helm:
    name: strimzi
    chart_ref: strimzi/strimzi-kafka-operator
    chart_version: 0.41.0
    release_namespace: strimzi
    create_namespace: true
    update_repo_cache: true


