# - name: Add a strimzi helm repository
#   kubernetes.core.helm_repository:
#     name: strimzi
#     repo_url: https://strimzi.io/charts

- name: Install strimzi
  kubernetes.core.helm:
    name: strimzi-cluster-operator
    chart_ref: oci://quay.io/strimzi-helm/strimzi-kafka-operator
    chart_version: 0.41.0
    release_namespace: strimzi
    create_namespace: true
    update_repo_cache: true

- name: Wait for deployments in strimzi namespace
  shell: bash /root/check_deployment.sh strimzi

