- name: Install registry
  kubernetes.core.helm:
    name: registry
    chart_ref: daas/registry
    release_namespace: sunbird-rc
    create_namespace: true
    update_repo_cache: true
    values:
      image_tag: v2.0.0
      rccoreenv:
        connectionInfo_uri: "{{registry_db_url}}"
        connectionInfo_username: "{{postgres_connectionInfo_username}}"
        connectionInfo_password: "{{postgres_connectionInfo_password}}"
        sunbird_sso_admin_client_secret: "{{sbrc_keycloak_admin_api_secret}}"
        filestorage_enabled: true
        filestorage_connection_url: http://filestorage:9000
        filestorage_secret_key: "{{filestorage_root_password}}"
        sunbird_sso_url: https://sbrciam.{{domain}}/auth
        oauth2_resource_uri: https://sbrciam.{{domain}}/auth/realms/sunbird-rc
        workflow.enable: 'true'
        claims_enabled: true
        signature_enabled: true
        did_enabled: true
        # credential_did_method: rcw
        # issuer_did_method : issuer
        # schema_author: Registry
        # schema_author_did_method: author
        did_health_check_url: http://identity-identity-service:3332/health 
        did_generate_url: http://identity-identity-service:3332/did/generate  
        did_resolve_url: http://identity-identity-service:3332/did/resolve  
        signature_v2_health_check_url: http://identity-credentials-service:3000/health
        signature_v2_issue_url: http://identity-credentials-service:3000/credentials/issue
        signature_v2_get_url: http://identity-credentials-service:3000/credentials/{id}
        signature_v2_delete_url: http://identity-credentials-service:3000/credentials/{id}
        signature_v2_verify_url:  http://identity-credentials-service:3000/credentials/{id}/verify
        signature_v2_revocation_list_url: http://identity-credentials-service:3000/credentials/revocation-list?issuerId={issuerDid}&page={page}&limit={limit}
        signature_v2_schema_health_check_url: http://identity-credential-schema-service:3333/health
        signature_v2_schema_create_url: http://identity-credential-schema-service:3333/credential-schema
        signature_v2_schema_update_url: "http://identity-credential-schema-service:3333/credential-schema/{id}/{version}"
        signature_v2_schema_get_by_id_and_version_url: "http://identity-credential-schema-service:3333/credential-schema/{id}/{version}"
        signature_v2_schema_search_by_tags_url: "http://identity-credential-schema-service:3333/credential-schema?tags={tags}"
        sign_url: http://certificatesign:8079/sign
        verify_url: http://certificatesign:8079/verify
        sign_health_check_url: http://certificatesign:8079/health
        certificate_enabled: true 
        pdf_url: http://certificateapi:8078/api/v1/certificatePDF
        certificate_health_check_url: http://certificateapi:8078/health

- name: Wait for deployments in sunbird-rc namespace
  shell: bash /root/check_deployment.sh sunbird-rc


- name: "Update registry virtual service config"
  template:
    src: "registry/registry-virtual-service.yaml.j2"
    dest: "/root/sunbird-rc/customization/registry/registry-virtual-service.yaml"

- name: Create registry virtual service
  shell: kubectl -n sunbird-rc apply -f /root/sunbird-rc/customization/registry/registry-virtual-service.yaml