- name: Add a prometheus helm repository
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts

- name: Install prometheus
  kubernetes.core.helm:
    name: prometheus
    chart_ref: prometheus-community/kube-prometheus-stack
    release_namespace: monitoring
    create_namespace: true
    update_repo_cache: true

- name: Wait for deployments in monitoring namespace
  shell: bash /root/check_deployment.sh monitoring

- name: "Update grafana virtual service config"
  template:
    src: "grafana/grafana_vs.yaml.j2"
    dest: "/root/openg2p/customization/grafana/grafana_vs.yaml"
    mode: '0755'

- name: "Create grafana virtual service"
  shell: |
    kubectl apply -n monitoring -f /root/openg2p/customization/grafana/grafana_vs.yaml