- name: Add a mosip helm repository
  kubernetes.core.helm_repository:
    name: mosip
    repo_url: https://mosip.github.io/mosip-helm

- name: Create global config directory
  file:
    path: "/root/kubernetes/config_server_secrets"
    state: directory
    mode: '0755'

- name: Copy install config server secrets scripts
  copy:
    src: install_config_server_secrets.sh
    dest: /root/kubernetes/config_server_secrets/install_config_server_secrets.sh
    mode: '0755'

- name: Install config server secrets
  shell: /root/kubernetes/config_server_secrets/install_config_server_secrets.sh