- name: Create global config directory
  file:
    path: "/root/kubernetes/global"
    state: directory
    mode: '0755'

- name: "Update global config"
  template:
    src: "global_config.j2"
    dest: "/root/kubernetes/global_config.yaml"

- name: Create global config map
  shell: kubectl apply -f /root/kubernetes/global_config.yaml