- name: Create global config directory
  file:
    path: "/root/mosip/minio"
    state: directory
    mode: '0755'

- name: Copy S3 credential setup scripts
  template:
    src: s3/cred.j2
    dest: "/root/mosip/minio/cred.sh"
    mode: '0755'

- name: S3 credential setup
  shell: bash /root/mosip/minio/cred.sh