- name: Add a traefik helm repository
  kubernetes.core.helm_repository:
    name: traefik
    repo_url: https://traefik.github.io/charts

- name: Create a k8s namespace
  kubernetes.core.k8s:
    name: "{{item}}"
    api_version: v1
    kind: Namespace
    state: present
  with_items:
    - traefik

- name: Upload ssl cert private key
  copy:
    src: "{{ ansible_ssl_cert_private_key_file }}"
    dest: "/root/.ssh/ssl_cert_private_key.key"
    mode: "0600"

- name: Upload ssl cert file
  copy:
    src: "{{ ansible_ssl_cert_file }}"
    dest: "/root/.ssh/ssl_cert.pem"
    mode: "0600"

- name: Create ssl secret for istio gateway
  shell: |
    kubectl -n traefik delete secret wildcard-ssl-tls
    kubectl create secret tls wildcard-ssl-tls -n traefik \
    --cert=/root/.ssh/ssl_cert.pem \
    --key=/root/.ssh/ssl_cert_private_key.key

- name: Remove ssl cert private key
  ansible.builtin.file:
    path: /root/.ssh/ssl_cert_private_key.key
    state: absent

- name: Remove ssl cert file
  ansible.builtin.file:
    path: /root/.ssh/ssl_cert.pem
    state: absent


- name: Install traefik
  kubernetes.core.helm:
    name: traefik
    chart_ref: traefik/traefik
    release_namespace: traefik
    chart_version: 28.3.0
    create_namespace: true
    update_repo_cache: true
    values:
      logs:
        general:
          level: DEBUG 
        access: 
          enabled: true 
      ports: 
        web: 
          asDefault: true
        websecure:
          tls:
            enabled: false
      tlsStore:
        default:
          defaultCertificate:
            secretName: wildcard-ssl-tls
      service:
        annotations: 
          oci.oraclecloud.com/load-balancer-type: "lb"
          service.beta.kubernetes.io/oci-load-balancer-internal: "true"
          service.beta.kubernetes.io/oci-load-balancer-backend-protocol: "HTTP"
          service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
          service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "100"
          service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
          service.beta.kubernetes.io/oci-load-balancer-ssl-ports: "443"
          oci.oraclecloud.com/oci-network-security-groups: "{{nsg_lb_oke_k8s_cluster}}"

- name: Wait for deployments in traefik namespace
  shell: bash /root/check_deployment.sh traefik


- name: Copy ingress routes
  template:
    src: "traefik/ingress_route.yaml.j2"
    dest: "/root/traefik/ingress_route.yaml"
    mode: '0755'

- name: Copy ingress routes
  template:
    src: "traefik/ingress_route_jaeger.yaml.j2"
    dest: "/root/traefik/ingress_route_jaeger.yaml"
    mode: '0755'

- name: Copy ingress
  template:
    src: "traefik/ingress.yaml.j2"
    dest: "/root/traefik/ingress.yaml"
    mode: '0755'

- name: Apply ingress routes
  shell: |
    kubectl apply -f /root/traefik/ingress_route.yaml

# - name: Apply ingress routes tracing
#   shell: |
#     kubectl apply -f /root/traefik/ingress_route_jaeger.yaml

# - name: Apply ingress
#   shell: |
#     kubectl apply -f /root/traefik/ingress.yaml