- name: "Copy rancher terraform files"
  template:
    src: "rancher.j2"
    dest: "/root/rancher/terraform/rancher.tf"
    mode: "0755"

- name: "Copy rancher bootstrap module terraform files"
  template:
    src: "bootstrap.j2"
    dest: "/root/rancher/terraform/bootstrap/bootstrap.tf"
    mode: "0755"


- name: "Execute rancher terraform"
  shell: |
    cd /root/rancher/terraform/
    tofu init
    tofu apply -auto-approve
