- name: Update apt cache
  apt:
    update_cache: yes

- name: Install dependencies
  package:
    name:
      - python3
      - python3-pip
      - curl
      - libpq-dev
      - postgresql
      - git

- name: Ignore PEP 668 because it's silly.
  ansible.builtin.file:
    path: /usr/lib/python3.12/EXTERNALLY-MANAGED
    state: absent

# - name: Install Pip3
#   apt:
#     name: python3-pip
#     update_cache: yes


# - name: Install dependencies
#   package:
#     name:
#       - python3
#       - curl
#       - libpq-dev
#       - postgresql
#       - git

- name: Install pip packages
  ansible.builtin.pip:
    name: 
      - kubernetes
      - psycopg2
      - pyOpenSSL
      - oci
      - oci-cli

- name: Remove OpenSSL python packages
  shell: |
    rm -R /usr/lib/python3/dist-packages/OpenSSL
    pip3 install pyOpenSSL --upgrade

- name: Install NVM
  shell: |
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash

- name: Install Node & Yarn
  shell: |
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
    nvm install {{node_version}}
    npm install --global yarn



# - name: set environment values
#   blockinfile:
#     path: /root/.bashrc
#     block: |
#       export KUBECONFIG=/root/.kube/oke_k8s_config
#       export PATH=/root/istio-1.21.0/bin:$PATH
#       alias k=kubectl
#       alias kctx=kubectx
#       alias kns=kubens
#     state: present
#     create: true